metric: VOC
map_type: 11point
num_classes: 1

TrainDataset:
  !VOCDataSet
    dataset_dir: /home/yuan/data/voc
    anno_path: /home/yuan/data/voc/train_list.txt
    label_list: /home/yuan/data/voc/labels.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: /home/yuan/data/voc/data/voc
    anno_path: /home/yuan/data/voc/val_list.txt
    label_list: /home/yuan/data/voc/labels.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: /home/yuan/data/voc/test_list.txt
